# Generated by Django 2.1.12 on 2020-01-11 17:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('City_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('No_Of_BedRooms', models.IntegerField(db_column='No_Of_BedRooms')),
                ('No_Of_LivingRooms', models.IntegerField(db_column='No_Of_LivingRooms')),
                ('No_Of_BathRooms', models.IntegerField(db_column='No_Of_BathRooms')),
                ('No_Of_Floors', models.IntegerField(db_column='No_Of_Floors')),
                ('Description', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=500)),
                ('AreaSqFt', models.FloatField()),
                ('Price', models.FloatField()),
                ('UserCreatedDate', models.DateField(default=datetime.datetime.today)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.City')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.Country')),
            ],
            options={
                'db_table': 'Property',
            },
        ),
        migrations.CreateModel(
            name='PropertyPurpose',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PropertyPurpose',
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PropertyStatus',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PropertyType',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('State_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.Country')),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='Property_Purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.PropertyPurpose'),
        ),
        migrations.AddField(
            model_name='property',
            name='Property_Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.PropertyStatus'),
        ),
        migrations.AddField(
            model_name='property',
            name='Property_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.PropertyType'),
        ),
        migrations.AddField(
            model_name='property',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.State'),
        ),
        migrations.AddField(
            model_name='property',
            name='UserCreatedBy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.State'),
        ),
    ]
