# Generated by Django 3.0.2 on 2020-01-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataproviderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='UserCreatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
