# Generated by Django 2.1.12 on 2019-12-24 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataproviderapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('City_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Country_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PropertyStatus',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PropertyType',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('State_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('FK_Country_ID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.Country')),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='FK_Country_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='FK_State_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataproviderapp.State'),
        ),
    ]
