# Generated by Django 3.0.2 on 2020-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataproviderapp', '0002_auto_20200112_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='LikedProperties',
            field=models.ManyToManyField(to='dataproviderapp.Property'),
        ),
    ]
