# Generated by Django 2.1.12 on 2019-12-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataproviderapp', '0004_auto_20191223_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='FK_Country_ID',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='FK_State_ID',
            new_name='State',
        ),
    ]
