# Generated by Django 3.0.2 on 2020-01-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataproviderapp', '0002_auto_20191014_2155'),
        ('dataproviderapp', '0005_auto_20191223_2142'),
    ]

    operations = [
    ]
